### ISSUE TITLE
진행 중에 발생한 문제점들

### ISSUE THREAD

**Issue by sihyun10** [sihyun10/hangman_game#2]
[문제점]
- 알파벳 버튼이 중복해 누를 수 있다.

![Animatd](https://github.com/sihyun10/hangman_game/assets/92582664/3168c3ff-9bb5-4373-9f0e-4f8e1c52c0d1)

위의 화면과 같이 해당 단어의 알파벳과 동일한 버튼 클릭하는것도 중복으로 클릭되고,
틀린것도 중복으로 클릭되어, 숫자도 계속 증가한다.
따라서 이렇게 되면 사용자가 무엇을 눌렀는지 모르고 계속 중복해서 누를 가능성이 있다.

**Comment by sihyun10** [comment]
![Animat](https://github.com/sihyun10/hangman_game/assets/92582664/e96c3944-af7f-438e-9918-a48900032b00)

```js
button.disabled = true;
```

```css
.alphabet button[disabled] {
  background-color: #CEF6D8;
  color: #f00;
  pointer-events: none;
}
```
